// Lang strings for d-awg-router-web
// Add new languages by adding entries to each map

package main

type LangMap map[string]string
type Langs map[string]LangMap

var langData = Langs{
	"en": LangMap{
		"page.title":       "d-awgRouter · VPN Manager",
		"tab.control":      "Control",
		"tab.services":     "Services",
		"tab.config":       "Config",
		"status.online":    "Online",
		"status.offline":   "Offline",
		"status.iface":     "Interface",
		"status.routes":    "Routes",
		"btn.up":           "UP",
		"btn.down":         "DOWN",
		"btn.restart":      "Restart",
		"btn.load_routes":  "Load Routes",
		"btn.save":         "Save",
		"btn.activate":     "Activate",
		"btn.delete":       "Delete",
		"btn.new":          "+ New",
		"btn.show_current": "Show Current",
		"config.title":     "Configurations",
		"config.new_name":  "New config name",
		"config.activated": "Activated. Restart VPN for change to take effect.",
		"config.deleted":   "Deleted",
		"config.saved":     "Saved",
		"config.empty_err": "Config is empty",
		"config.name_err":  "Enter config name",
		"confirm.down":     "Down VPN?",
		"confirm.restart":  "Restart VPN?",
		"confirm.delete":   "Delete config",
		"services.title":   "Services",
		"output.label":     "Output",
		"lang.label":       "Language",
		"s.output_iface": "=== I face ===",
		"s.output_routes": "=== Active Routes ===",
		"s.already_up":    "Already active on",
		"s.down_iface":    "brought down",
		"s.none_active":   "No active interface",
		"s.up_first":      "Run UP first",
		"s.updated":       "Routes updated on",
		"s.nets":          "subnets",
		"s.github_unavail":"GitHub unavailable, using cache",
		"s.cached":        "from cache",
		"s.loaded":        "loaded",
		"s.no_services":   "No services selected",
		"s.ok":            "OK",
		"s.fail":          "FAIL",
		"s.saved":         "Saved.",
		"s.save_err":      "Save error:",
		"s.config_needed": "Load a config first",
		"s.wg_up":         "WireGuard brought up on %s (via wireguard-go)",
		"s.awg_up":        "AmneziaWG brought up on %s",
	},
	"ru": LangMap{
		"page.title":       "d-awgRouter · VPN Менеджер",
		"tab.control":      "Управление",
		"tab.services":     "Сервисы",
		"tab.config":       "Конфиг",
		"status.online":    "В сети",
		"status.offline":   "Не в сети",
		"status.iface":     "Интерфейс",
		"status.routes":    "Маршруты",
		"btn.up":           "ВКЛ",
		"btn.down":         "ВЫКЛ",
		"btn.restart":      "Перезапуск",
		"btn.load_routes":  "Загрузить маршруты",
		"btn.save":         "Сохранить",
		"btn.activate":     "Активировать",
		"btn.delete":       "Удалить",
		"btn.new":          "+ Новая",
		"btn.show_current": "Текущий",
		"config.title":     "Конфигурации",
		"config.new_name":  "Новое название",
		"config.activated": "Активирован. Перезапустите VPN для применения.",
		"config.deleted":   "Удалён",
		"config.saved":     "Сохранён",
		"config.empty_err": "Конфиг пуст",
		"config.name_err":  "Введите название конфига",
		"confirm.down":     "Выключить VPN?",
		"confirm.restart":  "Перезапустить VPN?",
		"confirm.delete":   "Удалить конфиг",
		"services.title":   "Сервисы",
		"output.label":     "Вывод",
		"lang.label":       "Язык",
		"s.output_iface":   "=== Интерфейс ===",
		"s.output_routes":  "=== Активные маршруты ===",
		"s.already_up":     "Уже активен на",
		"s.down_iface":     "опущен",
		"s.none_active":    "Нет активного интерфейса",
		"s.up_first":       "Запустите UP сначала",
		"s.updated":        "Маршруты обновлены на",
		"s.nets":           "подсетей",
		"s.github_unavail": "GitHub недоступен, использую кэш",
		"s.cached":         "из кэша",
		"s.loaded":         "загружено",
		"s.no_services":    "Нет выбранных сервисов",
		"s.saved":          "Сохранено.",
		"s.save_err":       "Ошибка сохранения:",
		"s.config_needed":  "Загрузите конфиг сначала",
		"s.wg_up":          "WireGuard поднят на %s (через wireguard-go)",
		"s.awg_up":         "AmneziaWG поднят на %s",
	},
}
